version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
loggers:
  mosaic_engine:
    handlers: [console]
    level: DEBUG
    propagate: no
